name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.4
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'poetry.lock'



      - name: Install deps
        run: |
          poetry config virtualenvs.in-project true
          poetry install --with dev --no-interaction

      - name: Lint (pre-commit)
        run: |
          poetry run pre-commit run --all-files

      - name: Test
        run: |
          poetry run pytest -q
